https://hitagi.site:
  title: Kissshot - 快走吧,趁风暴来临前
  icon: https://hitagi.site/img/favicon.svg
https://element-plus.org/zh-CN/#/zh-CN:
  title: 一个 Vue 3 UI 框架 | Element Plus
  icon: https://element-plus.org/images/element-plus-logo-small.svg
https://developer.mozilla.org/zh-CN:
  title: MDN Web Docs
  icon: https://developer.mozilla.org/favicon-48x48.bc390275e955dacb2e65.png
